### ISSUE TITLE
Images won't load when plugin activated

### ISSUE THREAD

**Issue by itslukebond** [Mecanik/cloudflare-image-resizing#11]
Hello,

I've made sure that image resize is enabled, but when I enable the plugin my images on my site no longer load, they're just blank.

The end URL on them appears like this cdn-cgi/image/width=1000

Hope you can help

**Comment by Mecanik** [comment]
Hello,

It sounds like you have not enabled Image Resizing in your Cloudflare account?

**Comment by itslukebond** [comment]
It's 100% enabled. Images are still disappearing.

**Comment by kallinos95** [comment]
Hi, I am also facing the same issue but I think I got the services mixed up. Is Image Resizing a feature of the pro plan ($20 per month)? if yes, is there a way to use your plugin with just Cloudflare Images ($5 per month)?

**Comment by mdfathi99** [comment]
> It's 100% enabled. Images are still disappearing.

Hi, Try setting a dot `.` inside the Site URL setting instead of full site URL in the plugin setting.

**Comment by Mecanik** [comment]
I and nobody else can help without more information. You might have some HTML caching plugin or similar that prevents the changes from being visible.

From now on I will automatically close all similar threads without more information.
