### ISSUE TITLE
Suggestion: Prevent generation of local images

### ISSUE THREAD

**Issue by atsbob** [Mecanik/cloudflare-image-resizing#12]
I saw this in a plugin called Media Cloud. Do you think it might be possible to add an optional setting to disable local generation of thumbnails since manipulations would be handled from the master file? I'm thinking this could be good to save on local server space since the cropped generated sizes would not be served. Of course optional in case other users want to migrate back to local files.

**Comment by Mecanik** [comment]
> 

I`m frankly not aware of this plugin, however I will look into it.

**Comment by Mecanik** [comment]
I am closing this because after investigation this request is out of the scope of the plugin.
