### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by mrbm** [Mecanik/cloudflare-image-resizing#14]
Awesome work looking forward to trying it out! Before I dig in, couple questions:

1. How well does it work in a sub-fold multisite environment?
2. How would one go about transitioning images from [WP Offload Media Lite](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) with it using s3 for storage
3. Could it work with amazon s3 offline plugin where it gets priority over the s3 offline plugin

**Comment by mrbm** [comment]
are you making a "Functions" folder type worker? One thing that might worry me on those scenarios is all the bots using puppeteer and then eating up worker quotas for an account

**Comment by Mecanik** [comment]
> are you making a "Functions" folder type worker? One thing that might worry me on those scenarios is all the bots using puppeteer and then eating up worker quotas for an account

If you are talking about Pages, no. I made a regular Worker.

Whilst blocking puppeteer and bots is out of the scope of my project, that can be easily done from the Worker (also CF already does that).

On top of this, with my Worker HTML caching can be used. On top top of this, CF Images are cached once resized and you don't pay for accessing. On top top top of this, Workers have crazy Read limits... and more.

**Comment by mrbm** [comment]
looking forward to seeing what you make! Been playing alot with workers as well, fun stuff.
