### ISSUE TITLE
Broken image from Amazon

### ISSUE THREAD

**Issue by scorpiock** [Mecanik/cloudflare-image-resizing#16]
Hello,

First, nice plugin. It works like charm. 

All is well except Amazon images are broken coming through the AAWP plugin. Is there a way to instruct the plugin to rewrite images only from the given domain?

I've already unticked "Resize images from any origin" on Cloudflare.

**Comment by meneer-code** [comment]
I am also having this issue for external images, it does not write the external URL root

**Comment by Mecanik** [comment]
Hello,

Sorry for the late reply, been quite busy. External images should be ignored if they are not coming from your own domain, can you show me the result please?

**Comment by meneer-code** [comment]
I have created a pull request to solve this https://github.com/Mecanik/cloudflare-image-resizing/pull/17

**Comment by Mecanik** [comment]
Thanks, for some unknown reason I did not account for this (maybe they added this later). Anyway, regarding your pull request please see my comment.

**Comment by scorpiock** [comment]
Thank you for the quick action. Hope this gets merged soon so I can update the plugin.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
