### ISSUE TITLE
Broke my site's images

### ISSUE THREAD

**Issue by showmetech** [Mecanik/cloudflare-image-resizing#18]
Hello, just wanted to alert you that this plugin broke my site's images.

I've downloaded it, installed it on Wordpress, activated it and indicated my site's address. I've also enabled image conversion on cloudflare.

But what I've got was this: https://nimb.ws/po62lP

Let me know if you need any additional information, that might help fix this. Thanks.

**Comment by Mecanik** [comment]
Hello,

Please open your developer console (CTRL+SHIT+I) and share a screenshot of the errors so I can figure out what went wrong. Maybe your images are altered somehow through a plugin.

Thanks

**Comment by lakesidetechs** [comment]
Also having the same problem after activating plugin all the images on my site stopped loading. Enabled image conversion on cloudflare, made sure not to use worker routes /* for entire domain and entered the correct URL in the plugin settings. Images began loading again immediately after disabling the plugin. Received this error on the CloudFlare Image resizing dashboard "Origin returned 4xx HTTP status code". Will take a screenshot of the dev console and post during off hours. Thanks,

**Comment by Mecanik** [comment]
I need details, more specifically to see the developer console errors. Unfortunately I cannot simply guess what's happening there because there might be other plugins involved.

**Comment by mdfathi99** [comment]
Hi, I fetched the issue today. In the plugin setting page where you enter the Site URL, you might add your site's URL `https://example.com` or `example.com`.  Instead Only a dot `.` inside the Site URL field and click on Save and it will work.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
