### ISSUE TITLE
All images are gone after installing the code.

### ISSUE THREAD

**Issue by zoolbia** [Mecanik/cloudflare-image-resizing#19]
All images are gone after installing the code. here the link: [https://lagaiphone.se/](https://lagaiphone.se/)

![image](https://user-images.githubusercontent.com/22262003/181783099-714bf13c-c4ba-493b-a905-cdf497cac678.png)

**Comment by zoolbia** [comment]
Had to desable it for now, till solve the issue.... going to test on another site, with diffrent configuration....

**Comment by zoolbia** [comment]
The same problem... check [www.rey.se](url)
![image](https://user-images.githubusercontent.com/22262003/181785621-15e60ec7-45dd-499b-bee0-848d19b8437a.png)

**Comment by Mecanik** [comment]
I need details, more specifically to see the developer console errors. Unfortunately I cannot simply guess what's happening there because there might be other plugins involved.

**Comment by mdfathi99** [comment]
Hi, I fetched the issue today. In the plugin setting page where you enter the Site URL, you might add your site's URL `https://example.com` or `example.com`.  Instead Only a dot `.` inside the Site URL field and click on Save and it will work.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
