### ISSUE TITLE
Bug with iOS 16? 

### ISSUE THREAD

**Issue by berkmh** [Mecanik/cloudflare-image-resizing#21]
Since installing iOS 16 all avif images do not show on iPhone. Not sure if it is this plugin, cloudflare or apple is the problem....

**Comment by Mecanik** [comment]
Sounds like an amazing Apple issue. Has nothing to do with this plugin.

**Comment by berkmh** [comment]
hey after much back and forth with cloudflare here is what they found: 

"Thanks for your patience here, we were able to determine this is an issue with Appple's decorder which is currently affecting:

ios 16
mac os ventura beta
We have put a temporary workaround in place that will disable avif images when the option format=auto is being used.

We have reported this issue to apple and hope to have a permanent fix after they address the issue with their encoder.

Kind regards,

Sean Eustace
Technical Support Engineer - Cloudflare
"

so not sure if there is anything we need to update on this end or not? 

thanks
