### ISSUE TITLE
Feature Request: Resize only images with a certain class

### ISSUE THREAD

**Issue by meneer-code** [Mecanik/cloudflare-image-resizing#23]
Hey @Mecanik 

I'm keen to do another pull request if you can point me in the right direction.

I'd like to take a leaner approach for websites that have a LOT of images, and only resize the LCP element of each page, indicated by perhaps a class or data-attribute.

What do you think of this idea? Is it worth exploring or is it better to just hardcode the image URL in my template/function files?

Attached is an example of a LCP element prefetch in `wp_head`:
<img width="1185" alt="Screenshot 2022-09-22 at 09 33 56" src="https://user-images.githubusercontent.com/15004267/191686057-1852347c-bd36-4282-b7cc-7e9302f7cd2c.png">

**Comment by Mecanik** [comment]
Not a bad idea, I will consider it. If it doesn't impact performance I will add a feature for this.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
