### ISSUE TITLE
I've installed but not working

### ISSUE THREAD

**Issue by rnbjunk** [Mecanik/cloudflare-image-resizing#24]
I've installed the plugin on https://www.rnbjunk.com, but images seems not be serving.

**Comment by mdfathi99** [comment]
Hi @rnbjunk , I fetched the issue today. In the plugin setting page where you enter the Site URL, you might add your site's URL `https://example.com` or `example.com`.  Instead Only a dot `.` inside the Site URL field and click on Save and it will work.

**Comment by Mecanik** [comment]
Too many people installed the plugin already and it works out of the box. I have no idea what you are doing, it might be that you have some HTML cache plugin.

Without additional information nobody can help.
