### ISSUE TITLE
Image with a special crop set in page builder are defaulting to original aspect ratio

### ISSUE THREAD

**Issue by snowliondev** [Mecanik/cloudflare-image-resizing#28]
Using BeaverBuilder page builder if I set the thumbnails to a custom crop like "landscape" they appear in the original aspect ratio when then plugin is active. The dimensions of the crop at in the image files name so that is probably the cause.

`src="https://mysite.com/wp-content/uploads/bb-plugin/cache/image-1456x1024-landscape.jpg"`

**Comment by Mecanik** [comment]
This is a known problem with wordpress plugins... the only way to fix this is to rewrite images using workers.

I am still considering if I should make it open-source or not; because nobody actually cares to contribute to this plugin at the moment.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
