### ISSUE TITLE
A simple question, I can't find answer of on google.

### ISSUE THREAD

**Issue by itsOwen** [Mecanik/cloudflare-image-resizing#32]
Hello, I had some questions regarding the plugin, I would appreciate and even donate if the developer is likely to reply me back.

Q1. As stated in the description of the plugin, it changes all image urls, Does this mean it just shows a different url or it really changes the image url, Because my images are already indexed on google and by changing the url will my images get deranked or removed from search?

Q2. Will this store another instance of the newly created image on my server.

Q3. I can simply install it from the plugin installer right?

**Comment by RamConsulting** [comment]
I love this plugin - thanks so much for your work! For compatibility issues, I have needed to make the changes suggested in https://github.com/Mecanik/cloudflare-image-resizing/pull/22

Therefore you could consider making these changes after installing from the plugin installer, if you encounter problems with images not showing up after configuring your domain.

**Comment by itsOwen** [comment]
> Hello,
> 
> 1. It will show a different URL of the image inside the HTML output, it will not actually alter the original image URL; so indexing should not be affected at all. At least, nobody complained so far.
> 2. No
> 3. Yes
> 
> Thanks

Will this affect my seo, i mean the images that are already ranked will get removed because of the new urls?

**Comment by Mecanik** [comment]
> I love this plugin - thanks so much for your work! For compatibility issues, I have needed to make the changes suggested in #22
> 
> Therefore you could consider making these changes after installing from the plugin installer, if you encounter problems with images not showing up after configuring your domain.

Thanks. I cannot predict everything, and when someone needs help they usually reach you in private.

**Comment by itsOwen** [comment]
> > > Hello,
> > > 
> > > 1. It will show a different URL of the image inside the HTML output, it will not actually alter the original image URL; so indexing should not be affected at all. At least, nobody complained so far.
> > > 2. No
> > > 3. Yes
> > > 
> > > Thanks
> > 
> > 
> > Will this affect my seo, i mean the images that are already ranked will get removed because of the new urls? If you can help me doing a complete setup of the plugin according to my cloudflare settings it would help me a lot and I will donate as well for your hard work on this plugin
> 
> No, because the original image URLs stay in place.

Yo thanks man i tested this, Its pretty sick ngl, Website score went high from 33 to 78 on mobile and 99 on pc, Thanks for the help, I have made a pull request and added some images in readme so some people can easily understand what to do. If you want to merge you can thanks.

**Comment by Mecanik** [comment]
Thanks for the contribution. Approved.
