### ISSUE TITLE
Question re "Strip image sizes"

### ISSUE THREAD

**Issue by mdotk** [Mecanik/cloudflare-image-resizing#35]
I am seeing this in my source code for posts:

<img width="768" height="432" src="/cdn-cgi/image/width=1920,height=1080,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2023/07/image-768x432.jpg" ....

My understanding was that the "Strip image sizes" setting would take care of this? Otherwise, the "resizing" function would only ever be working off the thumbnail/smaller version of the image, and not the full sized one (eg image.jpg).

Great plugin otherwise!

**Comment by Mecanik** [comment]
There are 2 possible reasons why this cannot work:

- the config.php is not saved properly (CF_IMAGE_RESIZING_STRIP_SIZES)
- the regex used in the plugin fails

I need more information to look into it. Regardless, the result of images are better and faster.

**Comment by mdotk** [comment]
Actually I found your Cloudflare worker script and am now using that. Thanks!
