### ISSUE TITLE
Images not processed

### ISSUE THREAD

**Issue by Stirius** [Mecanik/cloudflare-image-resizing#37]
Hello, I have elementor on this site https://www.spots4kite.com/ and the homepage ignores resizing. It's not processed no matter what settings I use. I can activate all the integrations with no success...

The same on the map https://www.spots4kite.com/explore/?type=spots&sort=top-rated&category=freeride

Regards,
Karel

**Comment by GaneshRamDK** [comment]
Highly recommend using the CF Worker instead: https://github.com/Mecanik/cloudflare-image-resizing-worker

**Comment by Mecanik** [comment]
As Ganesh mentioned, please use the worker option (if you already tried enabling all hooks in the plugin).
