### ISSUE TITLE
Plugin rewriting Yoast schema image references

### ISSUE THREAD

**Issue by mdotk** [Mecanik/cloudflare-image-resizing#39]
Yoast outputs json_ld Schema like:

`url":"https://www.domains.com/wp-content/uploads/...`

But the plugin is rewriting it to:

`url":"/cdn-cgi/image/width=1920,height=1080,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/...`

How can I stop this? I tried changing the different hook numbers/levels in the plugin, but nothing worked.

**Comment by Mecanik** [comment]
This is because Yoast is most likely using a function that my plugin is hooking into as well. Frankly I do not see a solution for this because I cannot alter core functionality of wordpress. Please try the worker option.
