### ISSUE TITLE
"Some" images are not rewritten

### ISSUE THREAD

**Issue by star26bsd** [Mecanik/cloudflare-image-resizing#41]
Hello there ...

First of all, thanks for your plugin. We are using it on our site for many months and are generally happy.

I have noticed a glitch of which I am not sure it is related to the cloudflare image resizing plugin or to something else.

This is the environment:

**Related Plugins:**
- Plugin Version 1.5.4
- WordPress 6.4.3 with Hello theme version 3.0.1 including Hello child theme version 1.0.1 
- Cloudflare Plugin Version 4.12.4
- Elementor and Elementor Pro  3.19.2
- Readmedia Library Plugin version 4.22.7
- FooGallery (Premium) Version 2.4.7

**Cloudflare**:
Cloudflare Business plan including APO, also using the new "[transform](https://developers.cloudflare.com/images/transform-images/)" feature, that Cloudflare introduced recently.

**The effect I am seeing:**
When adding a Wordpress gallery, using the standard WP gallery 'feature', all images ARE properly rewrtitten to the CDN. Example:
https://www.ikigaido.ch/angebot/bonsai-karate/

When adding a FooGallery, the images are NOT rewritten to the CDN. Example: https://www.ikigaido.ch/galerie/karate/schweizermeisterschaft-2023-in-sursee/

When adding single images using Elementor, the image is SOMETIMES rewritten to the CDN. Working example: Front page https://www.ikigaido.ch with the lady in the karate suit. Non-Working example: https://www.ikigaido.ch/angebot/leistungssport-ftem-karate/ the first info graphics "FTEM Karate". Same page, the four portraits images of our squad are also not rwritten.

I am pulling my hair out in finding a pattern here. It seems obvious, that FooGallery is not supported. But why individual images are sometimes rewritten and sometimes not, I have no clue. Could it be related to the Cloudflare change related to the new transform plan?

Maybe you could have a look - I am happy to answer questions and provide more data.

Cheers
Stephan

**Comment by star26bsd** [comment]
Ok, I just discovered your article about the Worker solution. I will look into it.

**Comment by GaneshRamDK** [comment]
Hello,
I highly recommend using the working solution instead especially when using page builders: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/

Br,
Ganesh

**Comment by Mecanik** [comment]
Hello,

Thank you for the kind words. Indeed using the Plugin vs Worker has some ups and downs, which is specified in my original post.

The Worker can accommodate to any site/plugin, so that's the preferred option.

For future reference: Cloudflare renamed Image Resizing to Transform.
