### ISSUE TITLE
Css image-background

### ISSUE THREAD

**Issue by kirigamikinbaku** [Mecanik/cloudflare-image-resizing#7]
The plugin is amazing! It doesn't help when it comes to the css background

Do you think it can be implemented?

**Comment by kirigamikinbaku** [comment]
Also, I use simply gallery. images in native wp gallery use cloudflare, images in simply gallery styled galleries, and images in the lightbox don't use cloudflare

**Comment by Mecanik** [comment]
This can most likely be added, just need to have some time.

**Comment by kirigamikinbaku** [comment]
It would be amazing, the website is much faster with your plugin

**Comment by Mecanik** [comment]
I have been working on a full rewrite and this included attempts of adding this feature. Unfortunately it's really tricky because Wordpress does not offer any (proper) way of intercepting CSS; especially inline CSS.

But... I have some ideas that I have been testing, so could you provide an example website/URL where you have images inside CSS to inspect?

Thanks

**Comment by kirigamikinbaku** [comment]
www.ropetales.it

images on the homepage are part of css background

how about the galleries? did you add that feature by chance?

**Comment by Mecanik** [comment]
> [www.ropetales.it](http://www.ropetales.it)
> 
> images on the homepage are part of css background
> 
> how about the galleries? did you add that feature by chance?

Thanks, this is helpful. I have already finished the new plugin and tested on several websites with lots of images.

If you contact me via email I can give you a preview to test.

**Comment by Mecanik** [comment]
Hello, I am still waiting on your reply.

**Comment by DenisZando** [comment]
Hi there,
First, thank you for your plugin which work very well.
Second, like it is said here, is there an upcoming way to catch those background images coming from CSS ?
While kirigamikinbaku speak about galeries, I encounter this issue with Flipbox from builder like Elementor and co.
Here is the website I'm working on : [www.alpis.fr](https://www.alpis.fr/)

**Comment by Mecanik** [comment]
> 

I am not sure it's possible from within WP, as WP sucks. But I do have a solution view CF Workers.

**Comment by DenisZando** [comment]
> > 
> 
> I am not sure it's possible from within WP, as WP sucks. But I do have a solution view CF Workers.

Hi Mecanik and happy new year!
Have you been able to test those workers ?

**Comment by Mecanik** [comment]
> > > 
> > 
> > 
> > I am not sure it's possible from within WP, as WP sucks. But I do have a solution view CF Workers.
> 
> Hi Mecanik and happy new year! Have you been able to test those workers ?

Hello, yes and I am still considering whether to release it or not. 

Closing this thread because at the moment WordPress does not offer an option to re-write CSS on the fly.
